// Mocks generated by Mockito 5.4.4 from annotations
// in civic_connect/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:civic_connect/core/error/failures.dart' as _i5;
import 'package:civic_connect/features/auth/domain/entities/auth_entity.dart'
    as _i6;
import 'package:civic_connect/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:civic_connect/features/reports/domain/entities/report_entity.dart'
    as _i8;
import 'package:civic_connect/features/reports/domain/repositories/report_repository.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> register(_i6.AuthEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [entity],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #register,
            [entity],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>);
}

/// A class which mocks [ReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportRepository extends _i1.Mock implements _i7.ReportRepository {
  MockReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>> getReports() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReports,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ReportEntity>>(
          this,
          Invocation.method(
            #getReports,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>> getMyReports(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyReports,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ReportEntity>>(
          this,
          Invocation.method(
            #getMyReports,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ReportEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ReportEntity>> submitReport(
    _i8.ReportEntity? report,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReport,
          [
            report,
            imagePath,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ReportEntity>>.value(
                _FakeEither_0<_i5.Failure, _i8.ReportEntity>(
          this,
          Invocation.method(
            #submitReport,
            [
              report,
              imagePath,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ReportEntity>>);
}
